import { JSDOM } from "jsdom";
import { describe, expect, it } from "vitest";
import { extractProduct } from "./extract-product";
const page = (head: string) => new JSDOM(`<!doctype html><html><head>${head}</head><body></body></html>`, { url: "https://shop.example/products/chair?variant=1" }).window.document;
describe("extractProduct", () => {
  it("extracts Product JSON-LD and canonical URLs", () => { const document = page(`<link rel="canonical" href="https://shop.example/chair"><script type="application/ld+json">{"@type":"Product","name":"Marlow Chair","image":["https://cdn.example/chair.jpg"],"offers":{"price":"249.00","priceCurrency":"USD"}}</script>`); expect(extractProduct(document)).toMatchObject({ title: "Marlow Chair", imageUrl: "https://cdn.example/chair.jpg", price: "249.00", currency: "USD", sourceUrl: "https://shop.example/chair" }); });
  it("handles ProductGroup variants and AggregateOffer", () => { const document = page(`<script type="application/ld+json">{"@graph":[{"@type":"ProductGroup","name":"Cloud Sofa","offers":{"lowPrice":1299,"priceCurrency":"USD"},"hasVariant":[{"@type":"Product","name":"Cloud Sofa — Oat","image":{"contentUrl":"https://cdn.example/sofa.jpg"}}]}]}</script>`); expect(extractProduct(document)).toMatchObject({ title: "Cloud Sofa — Oat", imageUrl: "https://cdn.example/sofa.jpg", price: "1299", currency: "USD" }); });
  it("falls back to Open Graph and ignores malformed JSON-LD", () => { const document = page(`<meta property="og:title" content="Linen Lamp"><meta property="og:image" content="https://cdn.example/lamp.jpg"><meta property="product:price:amount" content="89"><meta property="product:price:currency" content="EUR"><script type="application/ld+json">{broken</script>`); expect(extractProduct(document)).toMatchObject({ title: "Linen Lamp", imageUrl: "https://cdn.example/lamp.jpg", price: "89", currency: "EUR" }); });
  it("falls back to visible commerce content on client-rendered pages", () => { const document = new JSDOM(`<!doctype html><html><body><main><h1>Dawn 93 Sofa</h1><picture><img src="https://cdn.example/dawn.jpg"></picture><div class="ProductPrice">$1499</div></main></body></html>`, { url: "https://www.article.com/product/dawn" }).window.document; expect(extractProduct(document)).toMatchObject({ title: "Dawn 93 Sofa", imageUrl: "https://cdn.example/dawn.jpg", price: "$1499" }); });

  it.each([
    ["IKEA", `<script type="application/ld+json">{"@type":"Product","name":"BINGSTA Armchair","image":{"@type":"ImageObject","contentUrl":"https://www.ikea.com/images/bingsta.jpg"},"offers":{"@type":"Offer","price":149.99,"priceCurrency":"USD"}}</script>`, { title: "BINGSTA Armchair", price: "149.99", currency: "USD" }],
    ["Article", `<script type="application/ld+json">{"@graph":[{"@type":["Product","FurnitureStore"],"name":"Dawn 93 Sofa - Silver Ivory","image":["https://cdn.article.com/dawn.jpg"],"offers":{"priceSpecification":{"price":1499,"priceCurrency":"USD"}}}]}</script>`, { title: "Dawn 93 Sofa - Silver Ivory", price: "1499", currency: "USD" }],
    ["West Elm", `<meta property="og:title" content="Morningside Swivel Chair"><meta property="og:image" content="https://assets.weimgs.com/chair.jpg"><meta property="product:price:amount" content="1399"><meta property="product:price:currency" content="USD">`, { title: "Morningside Swivel Chair", price: "1399", currency: "USD" }],
    ["CB2", `<script type="application/ld+json">{"@type":"ProductGroup","name":"Gwyneth Chair","image":"https://cb2.scene7.com/chair.jpg","offers":{"lowPrice":"999.00","priceCurrency":"USD"}}</script>`, { title: "Gwyneth Chair", price: "999.00", currency: "USD" }],
    ["Wayfair-style microdata", `<meta itemprop="name" content="Upholstered Accent Chair"><meta itemprop="image" content="https://secure.img1-fg.wfcdn.com/chair.jpg"><meta itemprop="price" content="286.99"><meta itemprop="priceCurrency" content="USD">`, { title: "Upholstered Accent Chair", price: "286.99", currency: "USD" }],
  ])("handles representative %s product markup", (_retailer, markup, expected) => {
    expect(extractProduct(page(markup))).toMatchObject(expected);
  });
});
